/// build.rs — compile-time codegen for the IPA phoneme feature database.
///
/// Reads `engine/assets/phonemes.json` once at *compile time*, emits
/// `$OUT_DIR/phonemes_data.rs` containing:
///
/// - `PHONEMES: &[(&str, [f32; 24])]`  — full feature matrix, sorted by IPA symbol
/// - `PHONEME_COUNT: usize`            — number of segments
/// - `PHONEME_DB_HASH: &str`           — FNV-1a hex digest of the canonical dataset
///
/// Nothing here runs at WASM startup. Zero JSON parsing in production.

use std::collections::BTreeMap;
use std::fmt::Write as FmtWrite;
use std::path::PathBuf;

// ── Canonical feature order (must match registry::FEATURE_NAMES) ──────────
const FEATURE_NAMES: [&str; 24] = [
    "syl", "son", "cons", "cont", "delrel", "lat", "nas", "strid",
    "voi", "sg", "cg", "ant", "cor", "distr", "lab", "hi", "lo",
    "back", "round", "velaric", "tense", "long", "hitone", "hireg",
];

// ── FNV-1a (64-bit) — no external deps needed ────────────────────────────
fn fnv1a(data: &str) -> u64 {
    const OFFSET: u64 = 14_695_981_039_346_656_037;
    const PRIME:  u64 = 1_099_511_628_211;
    let mut h = OFFSET;
    for b in data.bytes() {
        h ^= b as u64;
        h = h.wrapping_mul(PRIME);
    }
    h
}

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    // core crate is at engine/crates/core/ — assets are at engine/assets/
    let phonemes_path = manifest_dir.join("../../assets/phonemes.json");

    // Rerun only when the source data changes.
    println!("cargo:rerun-if-changed={}", phonemes_path.display());

    let raw = std::fs::read_to_string(&phonemes_path)
        .unwrap_or_else(|e| panic!("Cannot read {}: {e}", phonemes_path.display()));

    let db: serde_json::Value = serde_json::from_str(&raw)
        .expect("phonemes.json is not valid JSON");

    let phonemes = db["phonemes"]
        .as_array()
        .expect("phonemes.json must have a top-level \"phonemes\" array");

    // ── Build sorted map: IPA symbol → [f32; 24] ─────────────────────────
    // BTreeMap gives us alphabetical order → deterministic output & hash.
    let mut map: BTreeMap<String, [f32; 24]> = BTreeMap::new();

    for entry in phonemes {
        let ipa = entry["ipa"]
            .as_str()
            .expect("each phoneme entry must have an \"ipa\" string field");

        let features = entry["features"]
            .as_object()
            .expect("each phoneme entry must have a \"features\" object");

        let mut vec = [0f32; 24];
        for (i, name) in FEATURE_NAMES.iter().enumerate() {
            if let Some(feat) = features.get(*name) {
                vec[i] = match feat["value"].as_str().unwrap_or("0") {
                    "+" =>  1.0,
                    "-" => -1.0,
                    _   =>  0.0,
                };
            }
        }
        map.insert(ipa.to_string(), vec);
    }

    // ── Compute FNV-1a hash of canonical dataset ──────────────────────────
    // Canonical form: for each entry (sorted by IPA), write
    //   "{ipa}:{f0},{f1},...,{f23}\n"
    // This is stable across Rust versions, OSes, and JSON formatting.
    let mut canonical = String::with_capacity(map.len() * 80);
    for (ipa, vec) in &map {
        write!(canonical, "{ipa}:").unwrap();
        for (i, v) in vec.iter().enumerate() {
            if i > 0 { canonical.push(','); }
            // Encode as the raw f32 bits (hex) for exact reproducibility.
            write!(canonical, "{:08x}", v.to_bits()).unwrap();
        }
        canonical.push('\n');
    }
    let hash_u64 = fnv1a(&canonical);
    let hash_hex = format!("{hash_u64:016x}");

    // ── Generate Rust source ──────────────────────────────────────────────
    let mut src = String::with_capacity(map.len() * 200);

    writeln!(src, "// AUTO-GENERATED by build.rs — do not edit manually.").unwrap();
    writeln!(src, "// Source: engine/assets/phonemes.json").unwrap();
    writeln!(src).unwrap();

    writeln!(src, "/// FNV-1a (64-bit) hex digest of the canonical IPA phoneme dataset.").unwrap();
    writeln!(src, "/// Identical across all builds that use the same phonemes.json.").unwrap();
    writeln!(src, "pub const PHONEME_DB_HASH: &str = \"{hash_hex}\";").unwrap();
    writeln!(src).unwrap();

    writeln!(src, "pub const PHONEME_COUNT: usize = {};", map.len()).unwrap();
    writeln!(src).unwrap();

    writeln!(src, "/// Full IPA feature matrix embedded at compile time.").unwrap();
    writeln!(src, "/// Each entry: (ipa_symbol, [f32; 24]) in canonical FEATURE_NAMES order.").unwrap();
    writeln!(src, "/// Sorted by IPA symbol for deterministic output.").unwrap();
    writeln!(src, "pub static PHONEMES: &[(&str, [f32; 24])] = &[").unwrap();
    for (ipa, vec) in &map {
        // Escape any backslashes or quotes in the IPA string (edge case).
        let escaped = ipa.replace('\\', "\\\\").replace('"', "\\\"");
        let floats: Vec<String> = vec.iter().map(|v| format!("{v:.1}")).collect();
        writeln!(src, "    (\"{escaped}\", [{}]),", floats.join(", ")).unwrap();
    }
    writeln!(src, "];").unwrap();

    // ── Write to OUT_DIR ──────────────────────────────────────────────────
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    std::fs::write(out_dir.join("phonemes_data.rs"), &src)
        .expect("Cannot write phonemes_data.rs");

    eprintln!(
        "cargo:warning=phonemes_data.rs: {} segments, hash={}",
        map.len(),
        hash_hex
    );
}
