//! WebAssembly binding for the phonetic poetry engine.
//!
//! Exposes three functions to JavaScript / TypeScript:
//!
//! - `init(phonemesJson: string): void`  
//!   Load the feature registry (phonemes.json) once before any analysis.
//!
//! - `analyze(streamJson: string): string`  
//!   Accepts an IPA Stream v1.1 JSON document; returns a `StreamAnalysisResult`
//!   JSON string.
//!
//! - `version(): string`  
//!   Returns the supported IPA Stream format version string (`"1.1"`).
//!
//! ## Usage (browser / bundler)
//!
//! ```ts
//! import init_wasm, { init, analyze, version } from "ipa-poetry-engine";
//!
//! await init_wasm(); // load .wasm binary (wasm-pack adds this)
//!
//! const phonemesJson = await fetch("/assets/phonemes.json").then(r => r.text());
//! init(phonemesJson);   // one-time registry setup
//!
//! const result = JSON.parse(analyze(JSON.stringify(ipaStream)));
//! ```

use wasm_bindgen::prelude::*;

use phonetic_core::{FeatureRegistry, IpaStream, analyze_stream, FORMAT_VERSION};

// ────────────────────────────────────────────────────────────────────────────
// Global registry — initialised once, reused for every `analyze()` call.
// OnceLock is safe in single-threaded WASM environment.
// ────────────────────────────────────────────────────────────────────────────
static REGISTRY: std::sync::OnceLock<FeatureRegistry> = std::sync::OnceLock::new();

// ────────────────────────────────────────────────────────────────────────────
// Public WASM API
// ────────────────────────────────────────────────────────────────────────────

/// Load the phoneme feature registry from a JSON string.
///
/// Must be called **once** before `analyze()`. The registry is the content of
/// `phonemes.json` generated by the Panphon pipeline (~1 MB).
///
/// Throws if the JSON is malformed or if called more than once.
#[wasm_bindgen]
pub fn init(phonemes_json: &str) -> Result<(), JsError> {
    let registry = FeatureRegistry::from_json_bytes(phonemes_json.as_bytes())
        .map_err(|e| JsError::new(&format!("Failed to parse phonemes.json: {e}")))?;
    REGISTRY
        .set(registry)
        .map_err(|_| JsError::new("Registry already initialised — call init() only once"))?;
    Ok(())
}

/// Analyse an IPA Stream v1.1 JSON document.
///
/// Returns a `StreamAnalysisResult` serialised as a JSON string.  
/// Throws if:
/// - `init()` has not been called yet
/// - the input is not valid IPA Stream v1.1 JSON
/// - the stream format version does not match `"1.1"`
#[wasm_bindgen]
pub fn analyze(stream_json: &str) -> Result<String, JsError> {
    let registry = REGISTRY
        .get()
        .ok_or_else(|| JsError::new("Registry not initialised — call init(phonemesJson) first"))?;

    let stream = IpaStream::from_json_bytes(stream_json.as_bytes())
        .map_err(|e| JsError::new(&format!("Invalid IPA Stream JSON: {e}")))?;

    let result = analyze_stream(&stream, registry)
        .map_err(|e| JsError::new(&format!("Analysis error: {e}")))?;

    serde_json::to_string(&result)
        .map_err(|e| JsError::new(&format!("Serialisation error: {e}")))
}

/// Returns the IPA Stream format version this build supports (`"1.1"`).
#[wasm_bindgen]
pub fn version() -> String {
    FORMAT_VERSION.to_string()
}
