//! WebAssembly binding for the phonetic poetry engine.
//!
//! Exposes two functions to JavaScript / TypeScript:
//!
//! - `analyze(streamJson: string): string`  
//!   Accepts an IPA Stream v1.1 JSON document; returns a `StreamAnalysisResult`
//!   JSON string.
//!
//! - `version(): string`  
//!   Returns the supported IPA Stream format version string (`"1.1"`).
//!
//! The phoneme feature registry is **embedded at compile time** from
//! `engine/assets/phonemes.json` and initialised automatically on first use.
//! No manual `init()` call is required.
//!
//! ## Usage (browser / bundler)
//!
//! ```ts
//! import init_wasm, { analyze, version } from "ipa-poetry-engine";
//!
//! await init_wasm(); // load .wasm binary — registry auto-initialises
//!
//! const result = JSON.parse(analyze(JSON.stringify(ipaStream)));
//! ```

use wasm_bindgen::prelude::*;

use phonetic_core::{FeatureRegistry, IpaStream, analyze_stream, FORMAT_VERSION};
use phonetic_core::registry::PHONEME_DB_HASH;

// ────────────────────────────────────────────────────────────────────────────
// Global registry — built from the static array generated by core/build.rs.
// No JSON parsing at runtime. The feature vectors are f32 literals in the
// binary produced at compile time.
// ────────────────────────────────────────────────────────────────────────────
static REGISTRY: std::sync::OnceLock<FeatureRegistry> = std::sync::OnceLock::new();

fn registry() -> &'static FeatureRegistry {
    REGISTRY.get_or_init(FeatureRegistry::build)
}

// ────────────────────────────────────────────────────────────────────────────
// Public WASM API
// ────────────────────────────────────────────────────────────────────────────

/// Returns the FNV-1a (64-bit) hex digest of the embedded IPA phoneme database.
///
/// Identical for every binary built from the same `phonemes.json`.
/// Use this to verify that two consumers share the exact same IPA library.
#[wasm_bindgen(js_name = phonemeDbHash)]
pub fn phoneme_db_hash() -> String {
    PHONEME_DB_HASH.to_string()
}

/// Analyse an IPA Stream v1.1 JSON document.
///
/// Returns a `StreamAnalysisResult` serialised as a JSON string.  
/// Throws if:
/// - the input is not valid IPA Stream v1.1 JSON
/// - the stream format version does not match `"1.1"`
#[wasm_bindgen]
pub fn analyze(stream_json: &str) -> Result<String, JsError> {
    let stream = IpaStream::from_json_bytes(stream_json.as_bytes())
        .map_err(|e| JsError::new(&format!("Invalid IPA Stream JSON: {e}")))?;

    let result = analyze_stream(&stream, registry())
        .map_err(|e| JsError::new(&format!("Analysis error: {e}")))?;

    serde_json::to_string(&result)
        .map_err(|e| JsError::new(&format!("Serialisation error: {e}")))
}

/// Returns the IPA Stream format version this build supports (`"1.1"`).
#[wasm_bindgen]
pub fn version() -> String {
    FORMAT_VERSION.to_string()
}
